[common]
version = 2
import_std = [
    "fs",
    "net",
    "process",
    "unix_sockets",
]

[sandbox]
kind = "Disabled"

[api.process]
exclude = [
    "std::process::ExitCode",
    "std::process::ExitStatus",
]

[api.fs]
exclude = [
    "std::path",
]

[pkg.path_ratchet]
allow_unsafe = true
